# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "got"
      - dependency-name: "canvacord"
      - dependency-name: "delay"
      - dependency-name: "nekos.life"
      - dependency-name: "mongoose"
      - dependency-name: "chalk"
      - dependency-name: "google-play-scraper"
